// Every call into the Vetowall program goes through this module. It is the
// only file that reads the IDL, so swapping in the generated v2 IDL means
// checking the account and argument names here and nowhere else.
import { BN, EventParser, Program, type BorshInstructionCoder, type Idl } from '@anchor-lang/core';
import {
  PublicKey, SystemProgram, type AccountMeta, type TransactionInstruction, type VersionedTransactionResponse,
} from '@solana/web3.js';
import idl from './idl/vetowall.json';
import { connection } from './chain';
import { CLASSES, type Action, type ActionClass, type Snapshot } from './model';
import { describe, errorName, recordToAction, refusedAction, type DecodedRecord, type Routed } from './records';
import { TOKEN_2022, readMint } from './token';

// Anchor only needs a connection to build instructions and decode accounts;
// signing and sending happen in chain.ts.
const program = new Program(idl as Idl, { connection });
// Decoded accounts are untyped until the IDL is generated by the program build.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Decoded = any;
const accounts = program.account as unknown as Record<
  'config' | 'proposal' | 'reserve' | 'policy',
  {
    fetch(k: PublicKey): Promise<Decoded>;
    fetchNullable(k: PublicKey): Promise<Decoded | null>;
    all(filters: object[]): Promise<{ publicKey: PublicKey; account: Decoded }[]>;
  }
>;
export const PROGRAM_ID = program.programId;
const SYSVAR_IX = new PublicKey('Sysvar1nstructions1111111111111111111111111');

const find = (...seeds: (Buffer | Uint8Array)[]) => PublicKey.findProgramAddressSync(seeds, PROGRAM_ID)[0];
const s = (x: string) => Buffer.from(x);
const u64 = (n: number) => new BN(n).toArrayLike(Buffer, 'le', 8);

export const pda = {
  authority: (config: PublicKey) => find(s('authority'), config.toBuffer()),
  target: (config: PublicKey, program: PublicKey) => find(s('target'), config.toBuffer(), program.toBuffer()),
  policy: (config: PublicKey, program: PublicKey, disc: Uint8Array) =>
    find(s('policy'), config.toBuffer(), program.toBuffer(), disc),
  reserve: (config: PublicKey, mint: PublicKey) => find(s('reserve'), config.toBuffer(), mint.toBuffer()),
  proposal: (config: PublicKey, id: number) => find(s('proposal'), config.toBuffer(), u64(id)),
};

// The console only targets Token-2022 (disc_len = 1). Pausable (tag 44) is the
// one extension whose instructions it registers, so it's the only wide tag.
const WIDE_TAGS = [44];
export function discOf(data: Uint8Array): Uint8Array {
  const out = new Uint8Array(8);
  out.set(data.slice(0, WIDE_TAGS.includes(data[0]) ? 2 : 1));
  return out;
}

/** Anchor encodes a missing optional account as the program's own address. */
const opt = (k: PublicKey | null) => k ?? PROGRAM_ID;

const classArg = (c: ActionClass) => ({ [c.toLowerCase()]: {} });

/** The stored-instruction args plus the accounts the CPI needs at run time. */
function stored(ix: TransactionInstruction) {
  const metas = ix.keys.map((k) => ({ pubkey: k.pubkey, isSigner: k.isSigner, isWritable: k.isWritable }));
  // The authority PDA signs inside the program, never at the transaction level.
  const remaining: AccountMeta[] = [
    ...ix.keys.map((k) => ({ ...k, isSigner: false })),
    { pubkey: ix.programId, isSigner: false, isWritable: false },
  ];
  const policy = { target: ix.programId, disc: discOf(ix.data) };
  return { metas, remaining, data: Buffer.from(ix.data), policy };
}

function policyAccounts(config: PublicKey, target: PublicKey, disc: Uint8Array) {
  return { target: pda.target(config, target), policy: pda.policy(config, target, disc) };
}

// --- Setup (admin, before seal) ---------------------------------------------

export interface SetupParams {
  admin: PublicKey;
  config: PublicKey;
  mint: PublicKey;
  proposer: PublicKey;
  approver: PublicKey;
  guardian: PublicKey;
  attestor: PublicKey;
  delays: [number, number, number, number];
  /** Fast-lane cap per day, in base units. */
  dailyCap: bigint;
  /** Max reserve attestation age, seconds. */
  maxAge: number;
}

/** The issuer policy pack from docs/SPEC.md. SetAuthority and everything else stay `Max` by default. */
const POLICY_PACK: { disc: number[]; class: ActionClass; limited?: boolean }[] = [
  { disc: [7], class: 'Params', limited: true }, // MintTo
  { disc: [14], class: 'Params', limited: true }, // MintToChecked
  { disc: [10], class: 'Params' }, // FreezeAccount
  { disc: [11], class: 'Params' }, // ThawAccount
  { disc: [8], class: 'Authority' }, // Burn (permanent delegate)
  { disc: [15], class: 'Authority' }, // BurnChecked
  { disc: [44, 1], class: 'Safe' }, // Pausable: Pause
  { disc: [44, 2], class: 'Params' }, // Pausable: Resume
];

/** Instruction groups for setup, each small enough for one transaction. */
export async function setupIxs(p: SetupParams): Promise<TransactionInstruction[][]> {
  const reserve = pda.reserve(p.config, p.mint);
  const init = await program.methods
    .initialize(p.proposer, p.approver, p.guardian, p.delays.map((d) => new BN(d)))
    .accountsStrict({ admin: p.admin, config: p.config, systemProgram: SystemProgram.programId })
    .instruction();
  const initReserve = await program.methods
    .initReserve(p.mint, p.attestor, new BN(p.maxAge))
    .accountsStrict({ config: p.config, governor: p.admin, reserve, systemProgram: SystemProgram.programId })
    .instruction();
  const registers = await Promise.all(
    POLICY_PACK.map(({ disc, class: c, limited }) => {
      const d = discOf(Uint8Array.from(disc));
      const limit = limited
        ? { amountOffset: 1, cap: new BN(p.dailyCap.toString()), window: new BN(86400), reserve, mintIndex: 0 }
        : null;
      return program.methods
        .register(TOKEN_2022, [...d], 1, classArg(c), limit)
        .accountsStrict({ config: p.config, governor: p.admin, ...policyAccounts(p.config, TOKEN_2022, d), systemProgram: SystemProgram.programId })
        .instruction();
    }),
  );
  const seal = await program.methods.seal().accountsStrict({ config: p.config, admin: p.admin }).instruction();
  return [[init, initReserve], registers.slice(0, 4), [...registers.slice(4), seal]];
}

// --- Operating paths ----------------------------------------------------------

interface Roles {
  config: PublicKey;
  proposer: PublicKey;
  approver: PublicKey | null;
}

/** Fast lane: proposer and approver sign the same transaction. */
export async function executeNowIx(r: Roles, ix: TransactionInstruction, reserve: PublicKey | null) {
  const st = stored(ix);
  return program.methods
    .executeNow(st.policy.target, st.metas, st.data)
    .accountsStrict({
      config: r.config, proposer: r.proposer, approver: opt(r.approver),
      ...policyAccounts(r.config, st.policy.target, st.policy.disc),
      reserve: opt(reserve), instructions: SYSVAR_IX,
    })
    .remainingAccounts(st.remaining)
    .instruction();
}

export async function queueIx(r: Roles, ix: TransactionInstruction) {
  const st = stored(ix);
  const cfg = await accounts.config.fetch(r.config);
  return program.methods
    .queue(st.policy.target, st.metas, st.data)
    .accountsStrict({
      config: r.config, proposer: r.proposer, approver: opt(r.approver),
      proposal: pda.proposal(r.config, Number(cfg.proposalCount)),
      ...policyAccounts(r.config, st.policy.target, st.policy.disc),
      instructions: SYSVAR_IX, systemProgram: SystemProgram.programId,
    })
    .instruction();
}

/** Anyone can run a proposal once its timelock has passed. */
export async function executeIx(config: PublicKey, proposal: PublicKey, reserve: PublicKey | null) {
  const p = await accounts.proposal.fetch(proposal);
  const st = stored({
    programId: p.targetProgram,
    keys: p.accounts.map((m: { pubkey: PublicKey; isSigner: boolean; isWritable: boolean }) => ({ ...m })),
    data: Buffer.from(p.data),
  });
  const isMint = p.data[0] === 7 || p.data[0] === 14;
  return program.methods
    .execute()
    .accountsStrict({
      config, proposal, ...policyAccounts(config, st.policy.target, st.policy.disc),
      reserve: opt(isMint ? reserve : null), instructions: SYSVAR_IX,
    })
    .remainingAccounts(st.remaining)
    .instruction();
}

export async function attestIx(config: PublicKey, mint: PublicKey, attestor: PublicKey, amount: bigint) {
  return program.methods
    .attestReserve(new BN(amount.toString()))
    .accountsStrict({ reserve: pda.reserve(config, mint), attestor, instructions: SYSVAR_IX })
    .instruction();
}

export async function vetoIx(config: PublicKey, guardian: PublicKey, proposal: PublicKey, reason: Uint8Array) {
  return program.methods.veto([...reason]).accountsStrict({ config, guardian, proposal }).instruction();
}

/** The guardian's only way to act: run an instruction registered `Safe`, e.g. pause. */
export async function guardianExecuteIx(config: PublicKey, guardian: PublicKey, ix: TransactionInstruction) {
  const st = stored(ix);
  return program.methods
    .guardianExecute(st.policy.target, st.metas, st.data)
    .accountsStrict({ config, guardian, ...policyAccounts(config, st.policy.target, st.policy.disc), instructions: SYSVAR_IX })
    .remainingAccounts(st.remaining)
    .instruction();
}

// --- Reading -------------------------------------------------------------------

export async function isDeployed() {
  const info = await connection.getAccountInfo(PROGRAM_ID).catch(() => null);
  return !!info?.executable;
}

/** A config's reserve attestation as stored onchain. `amount` is in the mint's base units; times are unix seconds. */
export interface ReserveState {
  mint: PublicKey;
  attestor: PublicKey;
  amount: bigint;
  updatedAt: number;
  maxAge: number;
}

/**
 * Reads the first Reserve account that belongs to `config`, or null if it has none.
 *
 * This is the one read the attestation keeper needs. `loadSnapshot` finds the
 * same account but then walks the whole transaction history, which is hundreds
 * of RPC calls a scheduled job has no use for.
 */
export async function readReserve(config: PublicKey): Promise<ReserveState | null> {
  const found = (await accounts.reserve.all([{ memcmp: { offset: 8, bytes: config.toBase58() } }]))[0];
  if (!found) return null;
  const r = found.account;
  // The amount is a u64, which a JS number can't hold exactly; the times are i64 seconds, which it can for any real clock.
  return { mint: r.mint, attestor: r.attestor, amount: BigInt(r.amount.toString()), updatedAt: Number(r.updatedAt), maxAge: Number(r.maxAge) };
}

const variant = (e: object) => Object.keys(e)[0];
const hex = (b: number[]) => b.map((x) => x.toString(16).padStart(2, '0')).join('');

// --- Change records from transaction history ----------------------------------

const parser = new EventParser(PROGRAM_ID, program.coder);
const ixCoder = program.coder.instruction as BorshInstructionCoder;
// Confirmed transactions never change, so each is fetched and mapped once.
// ponytail: one entry per signature for the page's lifetime; fine for a console.
const seen = new Map<string, Action[]>();

/** Fast-lane, guardian, reserve and setup actions, and refused fast-lane attempts, read from chain. */
async function history(addresses: PublicKey[], decimals: number): Promise<Action[]> {
  // ponytail: newest 1000 signatures per address; page with `before` if a config outgrows that.
  const lists = [];
  for (const a of addresses) lists.push(await withRetry(() => connection.getSignaturesForAddress(a, { limit: 1000 })));
  const sigs = [...new Set(lists.flat().map((s) => s.signature))];
  // One request at a time: the public devnet RPC answers batched getTransactions
  // with 429. A transaction that still can't be fetched is skipped and retried on
  // the next refresh, so a rate limit thins the history instead of hiding it.
  for (const sig of sigs.filter((s) => !seen.has(s))) {
    const tx = await withRetry(() =>
      connection.getTransaction(sig, { maxSupportedTransactionVersion: 0, commitment: 'confirmed' }),
    ).catch(() => null);
    if (tx) seen.set(sig, actionsOf(tx, sig, decimals));
  }
  return sigs.flatMap((s) => seen.get(s) ?? []);
}

/** Retries rate-limited RPC calls with backoff (0.5s, 1s, 2s, 4s). */
async function withRetry<T>(call: () => Promise<T>): Promise<T> {
  for (let attempt = 0; ; attempt++) {
    try {
      return await call();
    } catch (e) {
      const limited = /429|Too many requests/i.test(String((e as Error)?.message ?? e));
      if (!limited || attempt >= 3) throw e;
      await new Promise((r) => setTimeout(r, 500 * 2 ** attempt));
    }
  }
}

/** Vetowall's top-level instructions in a transaction, decoded with the IDL. */
function vetowallIxs(tx: VersionedTransactionResponse) {
  const msg = tx.transaction.message;
  const keys = msg.getAccountKeys({ accountKeysFromLookups: tx.meta?.loadedAddresses });
  return msg.compiledInstructions
    .filter((ix) => keys.get(ix.programIdIndex)?.equals(PROGRAM_ID))
    .map((ix) => ({
      decoded: ixCoder.decode(Buffer.from(ix.data)),
      keys: ix.accountKeyIndexes.map((k) => keys.get(k)!.toBase58()),
    }));
}

function actionsOf(tx: VersionedTransactionResponse, sig: string, decimals: number): Action[] {
  const logs = tx.meta?.logMessages ?? [];
  const ixs = vetowallIxs(tx);
  if (tx.meta?.err) {
    // Failed transactions emit nothing; a refused fast-lane attempt is still evidence.
    const now = ixs.find((i) => i.decoded?.name === 'executeNow');
    if (!now) return [];
    const [, proposer, approver] = now.keys;
    const args = now.decoded!.data as Routed & { targetProgram: PublicKey };
    return [refusedAction(args, { proposer, approver: approver === PROGRAM_ID.toBase58() ? undefined : approver },
      errorName(logs), tx.blockTime ?? 0, sig, decimals)];
  }
  // Routed records pair, in order, with the routed instructions that produced them.
  const routed = ixs
    .filter((i) => i.decoded?.name === 'executeNow' || i.decoded?.name === 'guardianExecute')
    .map((i) => i.decoded!.data as Routed);
  const out: Action[] = [];
  for (const e of parser.parseLogs(logs)) {
    if (e.name !== 'changeRecord') continue;
    const r = e.data as DecodedRecord;
    const k = Object.keys(r.kind)[0];
    const a = recordToAction(r, sig, decimals, k === 'executedNow' || k === 'guardianExecuted' ? routed.shift() : undefined);
    if (a) out.push({ ...a, seq: out.length });
  }
  return out;
}

/**
 * Reads a live deployment. Without a mint, uses the mint of the config's
 * first Reserve. Returns null if the config doesn't exist.
 */
export async function loadSnapshot(config: PublicKey, mintHint?: PublicKey): Promise<Snapshot | null> {
  const cfg = await accounts.config.fetchNullable(config);
  if (!cfg) return null;
  const mint: PublicKey | undefined =
    mintHint ?? (await accounts.reserve.all([{ memcmp: { offset: 8, bytes: config.toBase58() } }]))[0]?.account.mint;
  if (!mint) return null;
  const reservePda = pda.reserve(config, mint);
  const [proposals, m, reserve, policy] = await Promise.all([
    accounts.proposal.all([{ memcmp: { offset: 8, bytes: config.toBase58() } }]),
    readMint(connection, mint),
    accounts.reserve.fetchNullable(reservePda),
    accounts.policy.fetchNullable(pda.policy(config, TOKEN_2022, discOf(Uint8Array.of(7)))),
  ]);
  const unit = 10 ** m.decimals;
  const proposer = cfg.proposer.toBase58();
  const approver = cfg.approver?.toBase58();
  const actions: Action[] = proposals.map(({ publicKey, account: p }) => {
    const status = variant(p.status) as Action['status'];
    const cls = CLASSES.find((c) => c.toLowerCase() === variant(p.class).toLowerCase()) ?? 'Max';
    return {
      id: Number(p.id),
      address: publicKey.toBase58(),
      path: 'timelock',
      ...describe(p.targetProgram.toBase58(), Uint8Array.from(p.data), p.accounts, m.decimals),
      class: cls,
      status,
      queuedAt: Number(p.queuedAt),
      eta: Number(p.eta),
      executedAt: Number(p.executedAt) || undefined,
      maker: proposer,
      checker: approver,
      vetoReason: status === 'vetoed' ? hex(p.vetoReason) : undefined,
    };
  });
  // attest_reserve doesn't take the config, so its records are found via the Reserve.
  // History is best-effort: live account state still renders if the RPC refuses it.
  actions.push(...(await history([config, reservePda], m.decimals).catch(() => [])));
  const now = Date.now() / 1000;
  const limit = policy?.limit;
  return {
    source: 'live',
    deployment: {
      config: config.toBase58(),
      authority: pda.authority(config).toBase58(),
      mint: mint.toBase58(),
      symbol: m.symbol,
      decimals: m.decimals,
      proposer,
      approver,
      guardian: cfg.guardian.toBase58(),
      attestor: reserve?.attestor.toBase58(),
      delays: cfg.delays.map(Number) as Snapshot['deployment']['delays'],
    },
    actions,
    supply: Number(m.supply) / unit,
    reserve: reserve
      ? { amount: Number(reserve.amount) / unit, updatedAt: Number(reserve.updatedAt), maxAge: Number(reserve.maxAge) }
      : null,
    cap: limit
      ? {
          cap: Number(limit.cap) / unit,
          // The program resets `used` lazily when a new window starts.
          used: now > Number(policy.windowStart) + Number(limit.window) ? 0 : Number(policy.used) / unit,
          windowStart: Number(policy.windowStart),
          window: Number(limit.window),
        }
      : null,
    authorities: m.authorities,
    paused: m.paused,
  };
}
