// Every call into the Vetowall program goes through this module. It is the
// only file that reads the IDL, so swapping in the generated v2 IDL means
// checking the account and argument names here and nowhere else.
import { BN, Program, type Idl } from '@anchor-lang/core';
import { PublicKey, SystemProgram, type AccountMeta, type TransactionInstruction } from '@solana/web3.js';
import idl from './idl/vetowall.json';
import { connection } from './chain';
import { CLASSES, type Action, type ActionClass, type Snapshot } from './model';
import { TOKEN_2022, readMint } from './token';

// Anchor only needs a connection to build instructions and decode accounts;
// signing and sending happen in chain.ts.
const program = new Program(idl as Idl, { connection });
// Decoded accounts are untyped until the IDL is generated by the program build.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Decoded = any;
const accounts = program.account as unknown as Record<
  'config' | 'proposal' | 'reserve' | 'policy',
  {
    fetch(k: PublicKey): Promise<Decoded>;
    fetchNullable(k: PublicKey): Promise<Decoded | null>;
    all(filters: object[]): Promise<{ publicKey: PublicKey; account: Decoded }[]>;
  }
>;
export const PROGRAM_ID = program.programId;
const SYSVAR_IX = new PublicKey('Sysvar1nstructions1111111111111111111111111');

const find = (...seeds: (Buffer | Uint8Array)[]) => PublicKey.findProgramAddressSync(seeds, PROGRAM_ID)[0];
const s = (x: string) => Buffer.from(x);
const u64 = (n: number) => new BN(n).toArrayLike(Buffer, 'le', 8);

export const pda = {
  authority: (config: PublicKey) => find(s('authority'), config.toBuffer()),
  target: (config: PublicKey, program: PublicKey) => find(s('target'), config.toBuffer(), program.toBuffer()),
  policy: (config: PublicKey, program: PublicKey, disc: Uint8Array) =>
    find(s('policy'), config.toBuffer(), program.toBuffer(), disc),
  reserve: (config: PublicKey, mint: PublicKey) => find(s('reserve'), config.toBuffer(), mint.toBuffer()),
  proposal: (config: PublicKey, id: number) => find(s('proposal'), config.toBuffer(), u64(id)),
};

// The console only targets Token-2022 (disc_len = 1). Pausable (tag 44) is the
// one extension whose instructions it registers, so it's the only wide tag.
const WIDE_TAGS = [44];
export function discOf(data: Uint8Array): Uint8Array {
  const out = new Uint8Array(8);
  out.set(data.slice(0, WIDE_TAGS.includes(data[0]) ? 2 : 1));
  return out;
}

/** Anchor encodes a missing optional account as the program's own address. */
const opt = (k: PublicKey | null) => k ?? PROGRAM_ID;

const classArg = (c: ActionClass) => ({ [c.toLowerCase()]: {} });

/** The stored-instruction args plus the accounts the CPI needs at run time. */
function stored(ix: TransactionInstruction) {
  const metas = ix.keys.map((k) => ({ pubkey: k.pubkey, isSigner: k.isSigner, isWritable: k.isWritable }));
  // The authority PDA signs inside the program, never at the transaction level.
  const remaining: AccountMeta[] = [
    ...ix.keys.map((k) => ({ ...k, isSigner: false })),
    { pubkey: ix.programId, isSigner: false, isWritable: false },
  ];
  const policy = { target: ix.programId, disc: discOf(ix.data) };
  return { metas, remaining, data: Buffer.from(ix.data), policy };
}

function policyAccounts(config: PublicKey, target: PublicKey, disc: Uint8Array) {
  return { target: pda.target(config, target), policy: pda.policy(config, target, disc) };
}

// --- Setup (admin, before seal) ---------------------------------------------

export interface SetupParams {
  admin: PublicKey;
  config: PublicKey;
  mint: PublicKey;
  proposer: PublicKey;
  approver: PublicKey;
  guardian: PublicKey;
  attestor: PublicKey;
  delays: [number, number, number, number];
  /** Fast-lane cap per day, in base units. */
  dailyCap: bigint;
  /** Max reserve attestation age, seconds. */
  maxAge: number;
}

/** The issuer policy pack from docs/SPEC.md. SetAuthority and everything else stay `Max` by default. */
const POLICY_PACK: { disc: number[]; class: ActionClass; limited?: boolean }[] = [
  { disc: [7], class: 'Params', limited: true }, // MintTo
  { disc: [14], class: 'Params', limited: true }, // MintToChecked
  { disc: [10], class: 'Params' }, // FreezeAccount
  { disc: [11], class: 'Params' }, // ThawAccount
  { disc: [8], class: 'Authority' }, // Burn (permanent delegate)
  { disc: [15], class: 'Authority' }, // BurnChecked
  { disc: [44, 1], class: 'Safe' }, // Pausable: Pause
  { disc: [44, 2], class: 'Params' }, // Pausable: Resume
];

/** Instruction groups for setup, each small enough for one transaction. */
export async function setupIxs(p: SetupParams): Promise<TransactionInstruction[][]> {
  const reserve = pda.reserve(p.config, p.mint);
  const init = await program.methods
    .initialize(p.proposer, p.approver, p.guardian, p.delays.map((d) => new BN(d)))
    .accountsStrict({ admin: p.admin, config: p.config, systemProgram: SystemProgram.programId })
    .instruction();
  const initReserve = await program.methods
    .initReserve(p.mint, p.attestor, new BN(p.maxAge))
    .accountsStrict({ config: p.config, governor: p.admin, reserve, systemProgram: SystemProgram.programId })
    .instruction();
  const registers = await Promise.all(
    POLICY_PACK.map(({ disc, class: c, limited }) => {
      const d = discOf(Uint8Array.from(disc));
      const limit = limited
        ? { amountOffset: 1, cap: new BN(p.dailyCap.toString()), window: new BN(86400), reserve, mintIndex: 0 }
        : null;
      return program.methods
        .register(TOKEN_2022, [...d], 1, classArg(c), limit)
        .accountsStrict({ config: p.config, governor: p.admin, ...policyAccounts(p.config, TOKEN_2022, d), systemProgram: SystemProgram.programId })
        .instruction();
    }),
  );
  const seal = await program.methods.seal().accountsStrict({ config: p.config, admin: p.admin }).instruction();
  return [[init, initReserve], registers.slice(0, 4), [...registers.slice(4), seal]];
}

// --- Operating paths ----------------------------------------------------------

interface Roles {
  config: PublicKey;
  proposer: PublicKey;
  approver: PublicKey | null;
}

/** Fast lane: proposer and approver sign the same transaction. */
export async function executeNowIx(r: Roles, ix: TransactionInstruction, reserve: PublicKey | null) {
  const st = stored(ix);
  return program.methods
    .executeNow(st.policy.target, st.metas, st.data)
    .accountsStrict({
      config: r.config, proposer: r.proposer, approver: opt(r.approver),
      ...policyAccounts(r.config, st.policy.target, st.policy.disc),
      reserve: opt(reserve), instructions: SYSVAR_IX,
    })
    .remainingAccounts(st.remaining)
    .instruction();
}

export async function queueIx(r: Roles, ix: TransactionInstruction) {
  const st = stored(ix);
  const cfg = await accounts.config.fetch(r.config);
  return program.methods
    .queue(st.policy.target, st.metas, st.data)
    .accountsStrict({
      config: r.config, proposer: r.proposer, approver: opt(r.approver),
      proposal: pda.proposal(r.config, Number(cfg.proposalCount)),
      ...policyAccounts(r.config, st.policy.target, st.policy.disc),
      instructions: SYSVAR_IX, systemProgram: SystemProgram.programId,
    })
    .instruction();
}

/** Anyone can run a proposal once its timelock has passed. */
export async function executeIx(config: PublicKey, proposal: PublicKey, reserve: PublicKey | null) {
  const p = await accounts.proposal.fetch(proposal);
  const st = stored({
    programId: p.targetProgram,
    keys: p.accounts.map((m: { pubkey: PublicKey; isSigner: boolean; isWritable: boolean }) => ({ ...m })),
    data: Buffer.from(p.data),
  });
  const isMint = p.data[0] === 7 || p.data[0] === 14;
  return program.methods
    .execute()
    .accountsStrict({
      config, proposal, ...policyAccounts(config, st.policy.target, st.policy.disc),
      reserve: opt(isMint ? reserve : null), instructions: SYSVAR_IX,
    })
    .remainingAccounts(st.remaining)
    .instruction();
}

export async function attestIx(config: PublicKey, mint: PublicKey, attestor: PublicKey, amount: bigint) {
  return program.methods
    .attestReserve(new BN(amount.toString()))
    .accountsStrict({ reserve: pda.reserve(config, mint), attestor, instructions: SYSVAR_IX })
    .instruction();
}

export async function vetoIx(config: PublicKey, guardian: PublicKey, proposal: PublicKey, reason: Uint8Array) {
  return program.methods.veto([...reason]).accountsStrict({ config, guardian, proposal }).instruction();
}

/** The guardian's only way to act: run an instruction registered `Safe`, e.g. pause. */
export async function guardianExecuteIx(config: PublicKey, guardian: PublicKey, ix: TransactionInstruction) {
  const st = stored(ix);
  return program.methods
    .guardianExecute(st.policy.target, st.metas, st.data)
    .accountsStrict({ config, guardian, ...policyAccounts(config, st.policy.target, st.policy.disc), instructions: SYSVAR_IX })
    .remainingAccounts(st.remaining)
    .instruction();
}

// --- Reading -------------------------------------------------------------------

export async function isDeployed() {
  const info = await connection.getAccountInfo(PROGRAM_ID).catch(() => null);
  return !!info?.executable;
}

const TOKEN_LABELS: Record<number, string> = {
  6: 'Change authority', 7: 'Mint', 8: 'Burn (permanent delegate)', 10: 'Freeze account',
  11: 'Thaw account', 14: 'Mint', 15: 'Burn (permanent delegate)',
};

function describe(target: PublicKey, data: Uint8Array, accounts: { pubkey: PublicKey }[], decimals: number) {
  if (target.equals(PROGRAM_ID)) return { action: 'Vetowall config change' };
  if (!target.equals(TOKEN_2022)) return { action: `Call to ${target.toBase58().slice(0, 4)}…` };
  if (data[0] === 44) return { action: data[1] === 1 ? 'Pause transfers' : 'Resume transfers' };
  const hasAmount = [7, 8, 14, 15].includes(data[0]) && data.length >= 9;
  return {
    action: TOKEN_LABELS[data[0]] ?? `Token-2022 instruction ${data[0]}`,
    subject: accounts[data[0] === 7 || data[0] === 14 ? 1 : 0]?.pubkey.toBase58(),
    amount: hasAmount ? Number(Buffer.from(data).readBigUInt64LE(1)) / 10 ** decimals : undefined,
  };
}

const variant = (e: object) => Object.keys(e)[0];
const hex = (b: number[]) => b.map((x) => x.toString(16).padStart(2, '0')).join('');

/**
 * Reads a live deployment. Without a mint, uses the mint of the config's
 * first Reserve. Returns null if the config doesn't exist.
 */
export async function loadSnapshot(config: PublicKey, mintHint?: PublicKey): Promise<Snapshot | null> {
  const cfg = await accounts.config.fetchNullable(config);
  if (!cfg) return null;
  const mint: PublicKey | undefined =
    mintHint ?? (await accounts.reserve.all([{ memcmp: { offset: 8, bytes: config.toBase58() } }]))[0]?.account.mint;
  if (!mint) return null;
  const [proposals, m, reserve, policy] = await Promise.all([
    accounts.proposal.all([{ memcmp: { offset: 8, bytes: config.toBase58() } }]),
    readMint(connection, mint),
    accounts.reserve.fetchNullable(pda.reserve(config, mint)),
    accounts.policy.fetchNullable(pda.policy(config, TOKEN_2022, discOf(Uint8Array.of(7)))),
  ]);
  const unit = 10 ** m.decimals;
  const proposer = cfg.proposer.toBase58();
  const approver = cfg.approver?.toBase58();
  const actions: Action[] = proposals.map(({ publicKey, account: p }) => {
    const status = variant(p.status) as Action['status'];
    const cls = CLASSES.find((c) => c.toLowerCase() === variant(p.class).toLowerCase()) ?? 'Max';
    return {
      id: Number(p.id),
      address: publicKey.toBase58(),
      path: 'timelock',
      ...describe(p.targetProgram, Uint8Array.from(p.data), p.accounts, m.decimals),
      class: cls,
      status,
      queuedAt: Number(p.queuedAt),
      eta: Number(p.eta),
      maker: proposer,
      checker: approver,
      vetoReason: status === 'vetoed' ? hex(p.vetoReason) : undefined,
    };
  });
  const now = Date.now() / 1000;
  const limit = policy?.limit;
  return {
    source: 'live',
    deployment: {
      config: config.toBase58(),
      authority: pda.authority(config).toBase58(),
      mint: mint.toBase58(),
      symbol: m.symbol,
      decimals: m.decimals,
      proposer,
      approver,
      guardian: cfg.guardian.toBase58(),
      attestor: reserve?.attestor.toBase58(),
      delays: cfg.delays.map(Number) as Snapshot['deployment']['delays'],
    },
    actions,
    supply: Number(m.supply) / unit,
    reserve: reserve
      ? { amount: Number(reserve.amount) / unit, updatedAt: Number(reserve.updatedAt), maxAge: Number(reserve.maxAge) }
      : null,
    cap: limit
      ? {
          cap: Number(limit.cap) / unit,
          // The program resets `used` lazily when a new window starts.
          used: now > Number(policy.windowStart) + Number(limit.window) ? 0 : Number(policy.used) / unit,
          windowStart: Number(policy.windowStart),
          window: Number(limit.window),
        }
      : null,
    authorities: m.authorities,
    paused: m.paused,
  };
}
